apply from: "$CONFIG.configDir/publish/base-artifact.gradle"

android {
  publishing {
    singleVariant("release") {
      withSourcesJar()
    }
  }
}

task androidSourceJar(type: Jar) {
  from android.sourceSets.main.java.srcDirs
  archiveClassifier = 'sources'
}

ext.androidArtifact = { Map config ->
  config = config ?: [:]

  return baseArtifact(config) << {
    from config.get('from') ?: components.release
  }
}
